//<![CDATA[
// Multi tab widget Sidebar
jQuery(document).ready(function($){ $(".multitab-widget-content-widget-id").hide(); $("ul.multitab-widget-content-tabs-id li:first a").addClass("multitab-widget-current").show(); $(".multitab-widget-content-widget-id:first").show(); $("ul.multitab-widget-content-tabs-id li a").click(function() { $("ul.multitab-widget-content-tabs-id li a").removeClass("multitab-widget-current a"); $(this).addClass("multitab-widget-current"); $(".multitab-widget-content-widget-id").hide(); var activeTab = $(this).attr("href"); $(activeTab).fadeIn(); return false; }); });
// Multi APPS and GAMES Windows
jQuery(document).ready(function($){ $(".multitab-widget-content-widget-windows").hide(); $("ul.multitab-widget-content-tabs-windows li:first a").addClass("multitab-widget-current-windows").show(); $(".multitab-widget-content-widget-windows:first").show(); $("ul.multitab-widget-content-tabs-windows li a").click(function() { $("ul.multitab-widget-content-tabs-windows li a").removeClass("multitab-widget-current-windows a"); $(this).addClass("multitab-widget-current-windows"); $(".multitab-widget-content-widget-windows").hide(); var activeTab = $(this).attr("href"); $(activeTab).fadeIn(); return false; }); });
// Multi APPS and GAMES Android
jQuery(document).ready(function($){ $(".multitab-widget-content-widget-android").hide(); $("ul.multitab-widget-content-tabs-android li:first a").addClass("multitab-widget-current-android").show(); $(".multitab-widget-content-widget-android:first").show(); $("ul.multitab-widget-content-tabs-android li a").click(function() { $("ul.multitab-widget-content-tabs-android li a").removeClass("multitab-widget-current-android a"); $(this).addClass("multitab-widget-current-android"); $(".multitab-widget-content-widget-android").hide(); var activeTab = $(this).attr("href"); $(activeTab).fadeIn(); return false; }); });
// Multi APPS and GAMES Linux
jQuery(document).ready(function($){ $(".multitab-widget-content-widget-linux").hide(); $("ul.multitab-widget-content-tabs-linux li:first a").addClass("multitab-widget-current-linux").show(); $(".multitab-widget-content-widget-linux:first").show(); $("ul.multitab-widget-content-tabs-linux li a").click(function() { $("ul.multitab-widget-content-tabs-linux li a").removeClass("multitab-widget-current-linux a"); $(this).addClass("multitab-widget-current-linux"); $(".multitab-widget-content-widget-linux").hide(); var activeTab = $(this).attr("href"); $(activeTab).fadeIn(); return false; }); });
//]]>
